#!/bin/bash
#BSUB -J md5calc[1-100]
#BSUB -o /data/talkowski/iwong/files/log_files/dupcaller100.log
#BSUB -e /data/talkowski/iwong/files/err_files/dupcalasf100.err
#BSUB -q big
#BSUB -n 5
#BSUB -M 8000
#BSUB -R rusage[mem=8000]
#BSUB swp=8G



source /etc/profile.d/00-modulepath.sh
source /etc/profile.d/z00_lmod.sh
module load Java/13.0.1

java -Xmx6G -jar /data/talkowski/iwong/src/jars/DMTK.jar calcMD5 /data/talkowski/iwong/data_management/tmp/dup_shard_${LSB_JOBINDEX} > /data/talkowski/iwong/data_management/tmp/md5_dup_${LSB_JOBINDEX}





