#!/bin/bash
#BSUB -J ncdu
#BSUB -o /data/talkowski/iwong/files/log_files/ncdu_15.log
#BSUB -e /data/talkowski/iwong/files/err_files/ncdu_15.err
#BSUB -q big
#BSUB -n 5
#BSUB mem=64G
#BSUB swp=64G
#BSUB sla miket_sc

DATE=$(date "+%Y-%m-%d-%H.%M.%S")

/data/talkowski/iwong/software/ncdu/ncdu -e -1xo- /data/talkowski/ | gzip > /data/talkowski/iwong/data_management/tmp/ncdu_${DATE}.gz
zcat /data/talkowski/iwong/data_management/tmp/ncdu_${DATE}.gz > /data/talkowski/iwong/data_management/tmp/ncdu.json

mv /data/talkowski/iwong/data_management/tmp/ncdu_${DATE}.gz /data/talkowski/iwong/data_management/ncdu_${DATE}.gz

OLD_FILE=$(ls -lhtr /data/talkowski/iwong/files/ncdu_cron_reports/ | grep "ncdu.*.gz" | head -1 | awk '{print $9}' )
#rm -rf /data/talkowski/iwong/files/ncdu_cron_reports/$OLD_FILE

date >> /data/talkowski/iwong/data_management/notes.txt
ls -lht /data/talkowski/iwong/data_management/ >> /data/talkowski/iwong/data_management/notes.txt




source /etc/profile.d/00-modulepath.sh
source /etc/profile.d/z00_lmod.sh
module load Java/13.0.1
java -Xmx64G -jar /data/talkowski/iwong/src/jars/DMTK.jar ncduParser /data/talkowski/iwong/data_management/tmp/ncdu.json /data/talkowski/iwong/data_management/file_sizes

java -Xmx64G -jar /data/talkowski/iwong/src/jars/DMTK.jar shame /data/talkowski/iwong/data_management/blacklist.txt /data/talkowski/iwong/data_management/personalDirectories.txt /data/talkowski/iwong/data_management/tmp/ncdu.json /data/talkowski/iwong/data_management/shame.txt

if [[ $(date +%u) == 6 ]]; then
bjobs -w
bjobs -w | grep "md5" | awk '{print $1}' | xargs bkill -r
bjobs -w | grep "MD5" | awk '{print $1}' | xargs bkill -r

java -Xmx64G -jar /data/talkowski/iwong/src/jars/DMTK.jar splitFiles /data/talkowski/iwong/data_management/file_sizes_sorted.tsv 100 /data/talkowski/iwong/data_management/tmp/dup_shard
bsub < /data/talkowski/iwong/src/scripts/calcmd5parallel.lsf
MY_ID=$(bjobs -w | grep "md5calc" | head -1 | awk '{print $1}')
bsub -w "numended(${MY_ID}, *)" < /data/talkowski/iwong/src/scripts/mergemd5files.lsf
fi





