#!/bin/bash
#BSUB -J mergeMD5
#BSUB -o /data/talkowski/iwong/files/log_files/dupcallerR100.log
#BSUB -e /data/talkowski/iwong/files/err_files/dupcalasf12eee.err
#BSUB -q big
#BSUB -n 5
#BSUB -M 16000
#BSUB -R rusage[mem=16000]
#BSUB swp=32G
#BSUB -sla miket_sc


source /etc/profile.d/00-modulepath.sh
source /etc/profile.d/z00_lmod.sh

cat /data/talkowski/iwong/data_management/tmp/md5_dup_* | grep -P "^/data/talkowski" > /data/talkowski/iwong/data_management/tmp/files_unsorted.txt
Rscipt /data/talkowski/iwong/src/scripts/mergeMD5files.R /data/talkowski/iwong/data_management/tmp/files_unsorted.txt /data/talkowski/iwong/data_management/file_sizes_sorted_md5.tsv
#rm -rf /data/talkowski/iwong/files/ncdu_cron_reports/tmp/dup_shard*
#rm -rf /data/talkowski/iwong/files/ncdu_cron_reports/tmp/md5*
java -Xmx32G -jar /data/talkowski/iwong/src/jars/DMTK.jar mergeFiles /data/talkowski/iwong/data_management/tmp/md5_dup 100 /data/talkowski/iwong/data_management/file_sizes_sorted_md5_dmtk.tsv


